# Generated by Django 5.0.6 on 2024-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
